// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/proto/mafia-server/mafia.proto

package mafia_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameState int32

const (
	GameState_NOT_STARTED GameState = 0
	GameState_RUNNING     GameState = 1
	GameState_FINISHED    GameState = 2
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "NOT_STARTED",
		1: "RUNNING",
		2: "FINISHED",
	}
	GameState_value = map[string]int32{
		"NOT_STARTED": 0,
		"RUNNING":     1,
		"FINISHED":    2,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_mafia_server_mafia_proto_enumTypes[0].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_pkg_proto_mafia_server_mafia_proto_enumTypes[0]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{0}
}

type DayStage int32

const (
	DayStage_DAY           DayStage = 0
	DayStage_NIGHT_MILITIA DayStage = 1
	DayStage_NIGHT_MAFIA   DayStage = 2
)

// Enum value maps for DayStage.
var (
	DayStage_name = map[int32]string{
		0: "DAY",
		1: "NIGHT_MILITIA",
		2: "NIGHT_MAFIA",
	}
	DayStage_value = map[string]int32{
		"DAY":           0,
		"NIGHT_MILITIA": 1,
		"NIGHT_MAFIA":   2,
	}
)

func (x DayStage) Enum() *DayStage {
	p := new(DayStage)
	*p = x
	return p
}

func (x DayStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DayStage) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_mafia_server_mafia_proto_enumTypes[1].Descriptor()
}

func (DayStage) Type() protoreflect.EnumType {
	return &file_pkg_proto_mafia_server_mafia_proto_enumTypes[1]
}

func (x DayStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DayStage.Descriptor instead.
func (DayStage) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{1}
}

type GetStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDead   bool   `protobuf:"varint,3,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	IsRobot  bool   `protobuf:"varint,4,opt,name=is_robot,json=isRobot,proto3" json:"is_robot,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

func (x *Player) GetIsRobot() bool {
	if x != nil {
		return x.IsRobot
	}
	return false
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId   string    `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Players   []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	State     GameState `protobuf:"varint,3,opt,name=state,proto3,enum=server.GameState" json:"state,omitempty"`
	DayStage  DayStage  `protobuf:"varint,4,opt,name=day_stage,json=dayStage,proto3,enum=server.DayStage" json:"day_stage,omitempty"`
	DayNumber int32     `protobuf:"varint,5,opt,name=day_number,json=dayNumber,proto3" json:"day_number,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *State) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *State) GetState() GameState {
	if x != nil {
		return x.State
	}
	return GameState_NOT_STARTED
}

func (x *State) GetDayStage() DayStage {
	if x != nil {
		return x.DayStage
	}
	return DayStage_DAY
}

func (x *State) GetDayNumber() int32 {
	if x != nil {
		return x.DayNumber
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{3}
}

func (x *Notification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetStateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State         *State          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Notifications []*Notification `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *GetStateReply) Reset() {
	*x = GetStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReply) ProtoMessage() {}

func (x *GetStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReply.ProtoReflect.Descriptor instead.
func (*GetStateReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{4}
}

func (x *GetStateReply) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetStateReply) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type ConnectLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId    string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
}

func (x *ConnectLobbyRequest) Reset() {
	*x = ConnectLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectLobbyRequest) ProtoMessage() {}

func (x *ConnectLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectLobbyRequest.ProtoReflect.Descriptor instead.
func (*ConnectLobbyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *ConnectLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type ConnectLobbyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectLobbyReply) Reset() {
	*x = ConnectLobbyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectLobbyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectLobbyReply) ProtoMessage() {}

func (x *ConnectLobbyReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectLobbyReply.ProtoReflect.Descriptor instead.
func (*ConnectLobbyReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{6}
}

type CreateLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName string `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type CreateLobbyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
}

func (x *CreateLobbyReply) Reset() {
	*x = CreateLobbyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyReply) ProtoMessage() {}

func (x *CreateLobbyReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyReply.ProtoReflect.Descriptor instead.
func (*CreateLobbyReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLobbyReply) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type StartGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId   string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	BotNumber int32  `protobuf:"varint,2,opt,name=bot_number,json=botNumber,proto3" json:"bot_number,omitempty"`
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{9}
}

func (x *StartGameRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *StartGameRequest) GetBotNumber() int32 {
	if x != nil {
		return x.BotNumber
	}
	return 0
}

type StartGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGameReply) Reset() {
	*x = StartGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameReply) ProtoMessage() {}

func (x *StartGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameReply.ProtoReflect.Descriptor instead.
func (*StartGameReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{10}
}

type ChooseAsMafiaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId       string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	ChoosedPlayer string `protobuf:"bytes,2,opt,name=choosed_player,json=choosedPlayer,proto3" json:"choosed_player,omitempty"`
}

func (x *ChooseAsMafiaRequest) Reset() {
	*x = ChooseAsMafiaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseAsMafiaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseAsMafiaRequest) ProtoMessage() {}

func (x *ChooseAsMafiaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseAsMafiaRequest.ProtoReflect.Descriptor instead.
func (*ChooseAsMafiaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{11}
}

func (x *ChooseAsMafiaRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *ChooseAsMafiaRequest) GetChoosedPlayer() string {
	if x != nil {
		return x.ChoosedPlayer
	}
	return ""
}

type ChooseAsMafiaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChooseAsMafiaReply) Reset() {
	*x = ChooseAsMafiaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseAsMafiaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseAsMafiaReply) ProtoMessage() {}

func (x *ChooseAsMafiaReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseAsMafiaReply.ProtoReflect.Descriptor instead.
func (*ChooseAsMafiaReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{12}
}

type ChooseAsMilitiaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId       string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	ChoosedPlayer string `protobuf:"bytes,2,opt,name=choosed_player,json=choosedPlayer,proto3" json:"choosed_player,omitempty"`
}

func (x *ChooseAsMilitiaRequest) Reset() {
	*x = ChooseAsMilitiaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseAsMilitiaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseAsMilitiaRequest) ProtoMessage() {}

func (x *ChooseAsMilitiaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseAsMilitiaRequest.ProtoReflect.Descriptor instead.
func (*ChooseAsMilitiaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{13}
}

func (x *ChooseAsMilitiaRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *ChooseAsMilitiaRequest) GetChoosedPlayer() string {
	if x != nil {
		return x.ChoosedPlayer
	}
	return ""
}

type ChooseAsMilitiaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChooseAsMilitiaReply) Reset() {
	*x = ChooseAsMilitiaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseAsMilitiaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseAsMilitiaReply) ProtoMessage() {}

func (x *ChooseAsMilitiaReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseAsMilitiaReply.ProtoReflect.Descriptor instead.
func (*ChooseAsMilitiaReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{14}
}

type FinishDayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
}

func (x *FinishDayRequest) Reset() {
	*x = FinishDayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishDayRequest) ProtoMessage() {}

func (x *FinishDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishDayRequest.ProtoReflect.Descriptor instead.
func (*FinishDayRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{15}
}

func (x *FinishDayRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type FinishDayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishDayReply) Reset() {
	*x = FinishDayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishDayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishDayReply) ProtoMessage() {}

func (x *FinishDayReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishDayReply.ProtoReflect.Descriptor instead.
func (*FinishDayReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{16}
}

type LynchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId        string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	GuiltyPlayerId string `protobuf:"bytes,2,opt,name=guilty_player_id,json=guiltyPlayerId,proto3" json:"guilty_player_id,omitempty"`
}

func (x *LynchRequest) Reset() {
	*x = LynchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LynchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LynchRequest) ProtoMessage() {}

func (x *LynchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LynchRequest.ProtoReflect.Descriptor instead.
func (*LynchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{17}
}

func (x *LynchRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *LynchRequest) GetGuiltyPlayerId() string {
	if x != nil {
		return x.GuiltyPlayerId
	}
	return ""
}

type LynchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LynchReply) Reset() {
	*x = LynchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LynchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LynchReply) ProtoMessage() {}

func (x *LynchReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_server_mafia_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LynchReply.ProtoReflect.Descriptor instead.
func (*LynchReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP(), []int{18}
}

var File_pkg_proto_mafia_server_mafia_proto protoreflect.FileDescriptor

var file_pkg_proto_mafia_server_mafia_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x44, 0x65, 0x61, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x73, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x12, 0x28,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x61,
	0x79, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x08, 0x64, 0x61, 0x79, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x22, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x70, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x51, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x35, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x58, 0x0a, 0x14, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d,
	0x61, 0x66, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65,
	0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x14, 0x0a,
	0x12, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x5a, 0x0a, 0x16, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x6f, 0x6f,
	0x73, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x16, 0x0a, 0x14, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x44, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x53, 0x0a, 0x0c, 0x4c, 0x79, 0x6e, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x67, 0x75, 0x69, 0x6c, 0x74, 0x79, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67,
	0x75, 0x69, 0x6c, 0x74, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0c, 0x0a,
	0x0a, 0x4c, 0x79, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x37, 0x0a, 0x09, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48,
	0x45, 0x44, 0x10, 0x02, 0x2a, 0x37, 0x0a, 0x08, 0x44, 0x61, 0x79, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x44, 0x41, 0x59, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x49, 0x47,
	0x48, 0x54, 0x5f, 0x4d, 0x49, 0x4c, 0x49, 0x54, 0x49, 0x41, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x4e, 0x49, 0x47, 0x48, 0x54, 0x5f, 0x4d, 0x41, 0x46, 0x49, 0x41, 0x10, 0x02, 0x32, 0xb3, 0x04,
	0x0a, 0x0b, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x3c, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x1b, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a,
	0x0d, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x12, 0x1c,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73,
	0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d, 0x61,
	0x66, 0x69, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0f, 0x43, 0x68,
	0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x61, 0x12, 0x1e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x41, 0x73, 0x4d,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a,
	0x09, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x44, 0x61, 0x79, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x44, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x05, 0x4c, 0x79, 0x6e, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x4c, 0x79, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x79, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x30, 0x34, 0x34, 0x32, 0x61, 0x34, 0x30, 0x33, 0x2e,
	0x68, 0x73, 0x65, 0x2e, 0x72, 0x75, 0x2f, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_mafia_server_mafia_proto_rawDescOnce sync.Once
	file_pkg_proto_mafia_server_mafia_proto_rawDescData = file_pkg_proto_mafia_server_mafia_proto_rawDesc
)

func file_pkg_proto_mafia_server_mafia_proto_rawDescGZIP() []byte {
	file_pkg_proto_mafia_server_mafia_proto_rawDescOnce.Do(func() {
		file_pkg_proto_mafia_server_mafia_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_mafia_server_mafia_proto_rawDescData)
	})
	return file_pkg_proto_mafia_server_mafia_proto_rawDescData
}

var file_pkg_proto_mafia_server_mafia_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_mafia_server_mafia_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_proto_mafia_server_mafia_proto_goTypes = []interface{}{
	(GameState)(0),                 // 0: server.GameState
	(DayStage)(0),                  // 1: server.DayStage
	(*GetStateRequest)(nil),        // 2: server.GetStateRequest
	(*Player)(nil),                 // 3: server.Player
	(*State)(nil),                  // 4: server.State
	(*Notification)(nil),           // 5: server.Notification
	(*GetStateReply)(nil),          // 6: server.GetStateReply
	(*ConnectLobbyRequest)(nil),    // 7: server.ConnectLobbyRequest
	(*ConnectLobbyReply)(nil),      // 8: server.ConnectLobbyReply
	(*CreateLobbyRequest)(nil),     // 9: server.CreateLobbyRequest
	(*CreateLobbyReply)(nil),       // 10: server.CreateLobbyReply
	(*StartGameRequest)(nil),       // 11: server.StartGameRequest
	(*StartGameReply)(nil),         // 12: server.StartGameReply
	(*ChooseAsMafiaRequest)(nil),   // 13: server.ChooseAsMafiaRequest
	(*ChooseAsMafiaReply)(nil),     // 14: server.ChooseAsMafiaReply
	(*ChooseAsMilitiaRequest)(nil), // 15: server.ChooseAsMilitiaRequest
	(*ChooseAsMilitiaReply)(nil),   // 16: server.ChooseAsMilitiaReply
	(*FinishDayRequest)(nil),       // 17: server.FinishDayRequest
	(*FinishDayReply)(nil),         // 18: server.FinishDayReply
	(*LynchRequest)(nil),           // 19: server.LynchRequest
	(*LynchReply)(nil),             // 20: server.LynchReply
}
var file_pkg_proto_mafia_server_mafia_proto_depIdxs = []int32{
	3,  // 0: server.State.players:type_name -> server.Player
	0,  // 1: server.State.state:type_name -> server.GameState
	1,  // 2: server.State.day_stage:type_name -> server.DayStage
	4,  // 3: server.GetStateReply.state:type_name -> server.State
	5,  // 4: server.GetStateReply.notifications:type_name -> server.Notification
	2,  // 5: server.MafiaEngine.GetState:input_type -> server.GetStateRequest
	7,  // 6: server.MafiaEngine.ConnectLobby:input_type -> server.ConnectLobbyRequest
	9,  // 7: server.MafiaEngine.CreateLobby:input_type -> server.CreateLobbyRequest
	11, // 8: server.MafiaEngine.StartGame:input_type -> server.StartGameRequest
	13, // 9: server.MafiaEngine.ChooseAsMafia:input_type -> server.ChooseAsMafiaRequest
	15, // 10: server.MafiaEngine.ChooseAsMilitia:input_type -> server.ChooseAsMilitiaRequest
	17, // 11: server.MafiaEngine.FinishDay:input_type -> server.FinishDayRequest
	19, // 12: server.MafiaEngine.Lynch:input_type -> server.LynchRequest
	6,  // 13: server.MafiaEngine.GetState:output_type -> server.GetStateReply
	8,  // 14: server.MafiaEngine.ConnectLobby:output_type -> server.ConnectLobbyReply
	10, // 15: server.MafiaEngine.CreateLobby:output_type -> server.CreateLobbyReply
	12, // 16: server.MafiaEngine.StartGame:output_type -> server.StartGameReply
	14, // 17: server.MafiaEngine.ChooseAsMafia:output_type -> server.ChooseAsMafiaReply
	16, // 18: server.MafiaEngine.ChooseAsMilitia:output_type -> server.ChooseAsMilitiaReply
	18, // 19: server.MafiaEngine.FinishDay:output_type -> server.FinishDayReply
	20, // 20: server.MafiaEngine.Lynch:output_type -> server.LynchReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_mafia_server_mafia_proto_init() }
func file_pkg_proto_mafia_server_mafia_proto_init() {
	if File_pkg_proto_mafia_server_mafia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectLobbyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseAsMafiaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseAsMafiaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseAsMilitiaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseAsMilitiaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishDayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishDayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LynchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_server_mafia_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LynchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_mafia_server_mafia_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_mafia_server_mafia_proto_goTypes,
		DependencyIndexes: file_pkg_proto_mafia_server_mafia_proto_depIdxs,
		EnumInfos:         file_pkg_proto_mafia_server_mafia_proto_enumTypes,
		MessageInfos:      file_pkg_proto_mafia_server_mafia_proto_msgTypes,
	}.Build()
	File_pkg_proto_mafia_server_mafia_proto = out.File
	file_pkg_proto_mafia_server_mafia_proto_rawDesc = nil
	file_pkg_proto_mafia_server_mafia_proto_goTypes = nil
	file_pkg_proto_mafia_server_mafia_proto_depIdxs = nil
}
